//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace FlyingClub.Data.Model
{
    public partial class instructorinfo
    {
        #region Primitive Properties
    
        public virtual long InstructorId
        {
            get;
            set;
        }
    
        public virtual string CertificateNumber
        {
            get;
            set;
        }
    
        public virtual string Ratings
        {
            get;
            set;
        }

        #endregion
    }
}
