//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace FlyingClub.Data.Model
{
    public partial class login
    {
        #region Primitive Properties
    
        public virtual long Id
        {
            get;
            set;
        }
    
        public virtual string Username
        {
            get;
            set;
        }
    
        public virtual string Password
        {
            get;
            set;
        }
    
        public virtual string Status
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<member> members
        {
            get
            {
                if (_members == null)
                {
                    var newCollection = new FixupCollection<member>();
                    newCollection.CollectionChanged += Fixupmembers;
                    _members = newCollection;
                }
                return _members;
            }
            set
            {
                if (!ReferenceEquals(_members, value))
                {
                    var previousValue = _members as FixupCollection<member>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmembers;
                    }
                    _members = value;
                    var newValue = value as FixupCollection<member>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmembers;
                    }
                }
            }
        }
        private ICollection<member> _members;

        #endregion
        #region Association Fixup
    
        private void Fixupmembers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (member item in e.NewItems)
                {
                    item.login = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (member item in e.OldItems)
                {
                    if (ReferenceEquals(item.login, this))
                    {
                        item.login = null;
                    }
                }
            }
        }

        #endregion
    }
}
