//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace FlyingClub.Data.Model
{
    public partial class NtxfcEntities : ObjectContext
    {
        public const string ConnectionString = "name=NtxfcEntities";
        public const string ContainerName = "NtxfcEntities";
    
        #region Constructors
    
        public NtxfcEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public NtxfcEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public NtxfcEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<aircraft> aircraft
        {
            get { return _aircraft  ?? (_aircraft = CreateObjectSet<aircraft>("aircraft")); }
        }
        private ObjectSet<aircraft> _aircraft;
    
        public ObjectSet<aircraftimage> aircraftimages
        {
            get { return _aircraftimages  ?? (_aircraftimages = CreateObjectSet<aircraftimage>("aircraftimages")); }
        }
        private ObjectSet<aircraftimage> _aircraftimages;
    
        public ObjectSet<instructorinfo> instructorinfoes
        {
            get { return _instructorinfoes  ?? (_instructorinfoes = CreateObjectSet<instructorinfo>("instructorinfoes")); }
        }
        private ObjectSet<instructorinfo> _instructorinfoes;
    
        public ObjectSet<login> logins
        {
            get { return _logins  ?? (_logins = CreateObjectSet<login>("logins")); }
        }
        private ObjectSet<login> _logins;
    
        public ObjectSet<member> members
        {
            get { return _members  ?? (_members = CreateObjectSet<member>("members")); }
        }
        private ObjectSet<member> _members;
    
        public ObjectSet<membercheckout> membercheckouts
        {
            get { return _membercheckouts  ?? (_membercheckouts = CreateObjectSet<membercheckout>("membercheckouts")); }
        }
        private ObjectSet<membercheckout> _membercheckouts;
    
        public ObjectSet<reservation> reservations
        {
            get { return _reservations  ?? (_reservations = CreateObjectSet<reservation>("reservations")); }
        }
        private ObjectSet<reservation> _reservations;
    
        public ObjectSet<role> roles
        {
            get { return _roles  ?? (_roles = CreateObjectSet<role>("roles")); }
        }
        private ObjectSet<role> _roles;
    
        public ObjectSet<squawk> squawks
        {
            get { return _squawks  ?? (_squawks = CreateObjectSet<squawk>("squawks")); }
        }
        private ObjectSet<squawk> _squawks;
    
        public ObjectSet<squawkcomment> squawkcomments
        {
            get { return _squawkcomments  ?? (_squawkcomments = CreateObjectSet<squawkcomment>("squawkcomments")); }
        }
        private ObjectSet<squawkcomment> _squawkcomments;

        #endregion
    }
}
