//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace FlyingClub.Data.Model
{
    public partial class reservation
    {
        #region Primitive Properties
    
        public virtual long Id
        {
            get;
            set;
        }
    
        public virtual long MemberId
        {
            get { return _memberId; }
            set
            {
                if (_memberId != value)
                {
                    if (member != null && member.Id != value)
                    {
                        member = null;
                    }
                    _memberId = value;
                }
            }
        }
        private long _memberId;
    
        public virtual long AircraftId
        {
            get { return _aircraftId; }
            set
            {
                if (_aircraftId != value)
                {
                    if (aircraft != null && aircraft.Id != value)
                    {
                        aircraft = null;
                    }
                    _aircraftId = value;
                }
            }
        }
        private long _aircraftId;
    
        public virtual System.DateTime StartTime
        {
            get;
            set;
        }
    
        public virtual System.DateTime EndTime
        {
            get;
            set;
        }
    
        public virtual string Status
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual aircraft aircraft
        {
            get { return _aircraft; }
            set
            {
                if (!ReferenceEquals(_aircraft, value))
                {
                    var previousValue = _aircraft;
                    _aircraft = value;
                    Fixupaircraft(previousValue);
                }
            }
        }
        private aircraft _aircraft;
    
        public virtual member member
        {
            get { return _member; }
            set
            {
                if (!ReferenceEquals(_member, value))
                {
                    var previousValue = _member;
                    _member = value;
                    Fixupmember(previousValue);
                }
            }
        }
        private member _member;

        #endregion
        #region Association Fixup
    
        private void Fixupaircraft(aircraft previousValue)
        {
            if (previousValue != null && previousValue.reservations.Contains(this))
            {
                previousValue.reservations.Remove(this);
            }
    
            if (aircraft != null)
            {
                if (!aircraft.reservations.Contains(this))
                {
                    aircraft.reservations.Add(this);
                }
                if (AircraftId != aircraft.Id)
                {
                    AircraftId = aircraft.Id;
                }
            }
        }
    
        private void Fixupmember(member previousValue)
        {
            if (previousValue != null && previousValue.reservations.Contains(this))
            {
                previousValue.reservations.Remove(this);
            }
    
            if (member != null)
            {
                if (!member.reservations.Contains(this))
                {
                    member.reservations.Add(this);
                }
                if (MemberId != member.Id)
                {
                    MemberId = member.Id;
                }
            }
        }

        #endregion
    }
}
